title: MTG Legacy UB Tempo Guide
description: >-
   UB Tempo is a strong and fun MTG Legacy deck but hard to play and get good with.
   Playing a lot certainly helps especially with experience playing other tempo decks but I believe a more structured learning process and community cooperation helps getting better faster.
   In the current day and age most of the discussion happens on sites like Discord and Reddit which are not optimized for cooperative knowledge sharing so as I'm comfortable with GitHub I will try it here.
   This guide is inspired by the excellent but currently unmaintained Delver Bible by Bob Huang.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kirdiemtg.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KonradHoeffner

# Build settings
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
# prevents the style element at the top of index.md from working
#  parse_block_html: true
  parse_block_html: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
